
function giveElements(){

dataelements = {
    nodes: [
        { id: "table1", group: 1 },
        { id: "table2", group: 1 },
        { id: "table3", group: 1 },
        { id: "table4", group: 1 },
        { id: "table5", group: 1 },
        { id: "table6", group: 1 },
        { id: "table7", group: 1 },
        { id: "table8", group: 1 },
        { id: "table9", group: 1 },
        { id: "table10", group: 1 },
        { id: "table11", group: 1 },
        { id: "table12", group: 1 },
        { id: "table13", group: 1 },
        { id: "table14", group: 1 },
        { id: "table15", group: 1 },
        { id: "table16", group: 1 },
        { id: "table17", group: 1 },
        { id: "table18", group: 1 },
        { id: "table19", group: 1 },
        { id: "table20", group: 1 },
        { id: "table21", group: 1 },
        { id: "table22", group: 1 },
        { id: "table23", group: 1 },
        { id: "table24", group: 1 },
        { id: "table25", group: 1 },
        { id: "table26", group: 1 },
        { id: "table27", group: 1 },
        { id: "table28", group: 1 },
        { id: "table29", group: 1 },
        { id: "table30", group: 1 },
        { id: "table31", group: 1 },
        { id: "table32", group: 1 },
        { id: "table33", group: 1 },
        { id: "table34", group: 1 },
        { id: "table35", group: 1 },
        { id: "table36", group: 1 },
        { id: "table37", group: 1 },
        { id: "table38", group: 1 },
        { id: "table39", group: 1 },
        { id: "table40", group: 1 },
        { id: "table41", group: 1 },
        { id: "table42", group: 1 },
        { id: "table43", group: 1 },
        { id: "table44", group: 1 },
        { id: "table45", group: 1 },
        { id: "table46", group: 1 },
        { id: "table47", group: 1 },
        { id: "table48", group: 1 },
        { id: "table49", group: 1 },
        { id: "table50", group: 1 },


        { id: "svc1", group: 2 },
        { id: "svc2", group: 2 },
        { id: "svc3", group: 2 },
        { id: "svc4", group: 2 },
        { id: "svc5", group: 2 },
        { id: "svc6", group: 2 },
        { id: "svc7", group: 2 },
        { id: "svc8", group: 2 },
        { id: "svc9", group: 2 },
        { id: "svc10", group: 2 },


        { id: "web1", group: 3 },
        { id: "web2", group: 3 },
        { id: "web3", group: 3 },
        { id: "web4", group: 3 },
        { id: "web5", group: 3 },
        { id: "web6", group: 3 },
        { id: "web7", group: 3 },
        { id: "web8", group: 3 },
        { id: "web9", group: 3 },
        { id: "web10", group: 3 },

        { id: "batch1", group: 4 },
        { id: "batch2", group: 4 },
        { id: "batch3", group: 4 },
        { id: "batch4", group: 4 },
        { id: "batch5", group: 4 },
        { id: "batch6", group: 4 },
        { id: "batch7", group: 4 },
        { id: "batch8", group: 4 },
        { id: "batch9", group: 4 },
        { id: "batch10", group: 4 },


    ],

    links: [
        { source: "table1", target: "svc1", value: 1 },
        { source: "table1", target: "svc3", value: 1 },
        { source: "table1", target: "svc4", value: 1 },
        { source: "table1", target: "svc5", value: 1 },
        { source: "table2", target: "svc1", value: 1 },
        { source: "table3", target: "svc1", value: 1 },
        { source: "table4", target: "svc2", value: 1 },
        { source: "table2", target: "svc2", value: 1 },
        { source: "table5", target: "svc2", value: 1 },

        { source: "table1", target: "svc2", value: 1 },
        { source: "table4", target: "svc2", value: 1 },
        { source: "table5", target: "svc2", value: 1 },
        { source: "table6", target: "svc2", value: 1 },
        { source: "table7", target: "svc2", value: 1 },
        { source: "table8", target: "svc2", value: 1 },
        { source: "table9", target: "svc2", value: 1 },
        { source: "table10", target: "svc2", value: 1 },
        { source: "table11", target: "svc2", value: 1 },
        { source: "table12", target: "svc2", value: 1 },
        { source: "table13", target: "svc2", value: 1 },
        { source: "table14", target: "svc2", value: 1 },
        { source: "table15", target: "svc2", value: 1 },
        { source: "table16", target: "svc2", value: 1 },
        { source: "table17", target: "svc2", value: 1 },
        { source: "table18", target: "svc2", value: 1 },
        { source: "table19", target: "svc2", value: 1 },
        { source: "table20", target: "svc2", value: 1 },
        { source: "table21", target: "svc2", value: 1 },
        { source: "table22", target: "svc2", value: 1 },
        { source: "table23", target: "svc2", value: 1 },
        { source: "table24", target: "svc2", value: 1 },
        { source: "table25", target: "svc2", value: 1 },
        { source: "table26", target: "svc2", value: 1 },
        { source: "table27", target: "svc2", value: 1 },
        { source: "table28", target: "svc2", value: 1 },
        { source: "table29", target: "svc2", value: 1 },
        { source: "table30", target: "svc2", value: 1 },
        { source: "table31", target: "svc2", value: 1 },
        { source: "table32", target: "svc2", value: 1 },
        { source: "table33", target: "svc2", value: 1 },
        { source: "table34", target: "svc2", value: 1 },
        { source: "table35", target: "svc2", value: 1 },
        { source: "table36", target: "svc2", value: 1 },
        { source: "table37", target: "svc2", value: 1 },
        { source: "table38", target: "svc2", value: 1 },
        { source: "table39", target: "svc2", value: 1 },
        { source: "table40", target: "svc2", value: 1 },
        { source: "table41", target: "svc2", value: 1 },
        { source: "table42", target: "svc2", value: 1 },
        { source: "table43", target: "svc2", value: 1 },
        { source: "table44", target: "svc2", value: 1 },
        { source: "table45", target: "svc2", value: 1 },
        { source: "table46", target: "svc2", value: 1 },
        { source: "table47", target: "svc2", value: 1 },
        { source: "table48", target: "svc2", value: 1 },
        { source: "table49", target: "svc2", value: 1 },
        { source: "table50", target: "svc2", value: 1 },

        { source: "table4", target: "svc2", value: 1 },
        { source: "table5", target: "svc2", value: 1 },
        { source: "table6", target: "svc2", value: 1 },
        { source: "table7", target: "svc2", value: 1 },
        { source: "table8", target: "svc2", value: 1 },
        { source: "table9", target: "svc2", value: 1 },
        { source: "table10", target: "svc2", value: 1 },
        { source: "table11", target: "svc2", value: 1 },
        { source: "table12", target: "svc2", value: 1 },
        { source: "table13", target: "svc2", value: 1 },
        { source: "table14", target: "svc2", value: 1 },
        { source: "table15", target: "svc2", value: 1 },

        { source: "table4", target: "batch2", value: 1 },
        { source: "table5", target: "batch2", value: 1 },
        { source: "table6", target: "batch2", value: 1 },
        { source: "table7", target: "batch2", value: 1 },
        { source: "table8", target: "batch2", value: 1 },
        { source: "table9", target: "batch2", value: 1 },
        { source: "table10", target: "batch2", value: 1 },
        { source: "table11", target: "batch2", value: 1 },
        { source: "table12", target: "batch2", value: 1 },
        { source: "table13", target: "batch2", value: 1 },
        { source: "table14", target: "batch2", value: 1 },
        { source: "table15", target: "batch2", value: 1 },

        { source: "web4", target: "svc2", value: 1 },
        { source: "web5", target: "svc2", value: 1 },
        { source: "web6", target: "svc2", value: 1 },
        { source: "web7", target: "svc2", value: 1 },
        { source: "web8", target: "svc2", value: 1 },
        { source: "web8", target: "svc1", value: 1 },
        { source: "web9", target: "svc2", value: 1 },
        { source: "web10", target: "svc2", value: 1 },
        { source: "web10", target: "svc1", value: 1 }

    ]
};

return dataelements;
}
