
function giveElements(){

dataelements = {
    nodes: [
        { id: "ACCOUNT1", group: 1 },
        { id: "ACCOUNT2", group: 1 },
        { id: "ACCOUNT3", group: 1 },
        { id: "ACCOUNT4", group: 1 },
        { id: "ACCOUNT5", group: 1 },
        { id: "ACCOUNT6", group: 1 },
        { id: "ACTIVITY1", group: 1 },
        { id: "ACTIVITY2", group: 1 },
        { id: "ACTIVITY3", group: 1 },
        { id: "ACTIVITY4", group: 1 },
        { id: "ACTIVITY5", group: 1 },
        { id: "ACTIVITY6", group: 1 },
        { id: "FPA1", group: 4 },
        { id: "FPA2", group: 4 },
        { id: "FPA3", group: 4 },
        { id: "FPA4", group: 4 },
        { id: "FPA5", group: 4 },
        { id: "ICP1", group: 4 },
        { id: "ICP2", group: 4 },
        { id: "ICP3", group: 4 },
        { id: "ICP4", group: 4 },
        { id: "ICP5", group: 4 },
        { id: "LEDGER1", group: 1 },
        { id: "LEDGER2", group: 1 },
        { id: "LEDGER3", group: 1 },
        { id: "LEDGER4", group: 1 },
        { id: "LEDGER5", group: 1 },
        { id: "LEDGER6", group: 1 },
        { id: "PEOPLE1", group: 1 },
        { id: "PEOPLE2", group: 1 },
        { id: "PEOPLE3", group: 1 },
        { id: "PEOPLE4", group: 1 },
        { id: "PEOPLE5", group: 1 },
        { id: "PEOPLE6", group: 1 },
        { id: "PROJECT1", group: 1 },
        { id: "PROJECT2", group: 1 },
        { id: "PROJECT3", group: 1 },
        { id: "PROJECT4", group: 1 },
        { id: "PROJECT5", group: 1 },
        { id: "PROJECT6", group: 1 },
        { id: "PSA1", group: 4 },
        { id: "PSA2", group: 4 },
        { id: "PSA3", group: 4 },
        { id: "PSA4", group: 4 },
        { id: "PSA5", group: 4 },
        { id: "PTX1", group: 4 },
        { id: "PTX2", group: 4 },
        { id: "PTX3", group: 4 },
        { id: "PTX4", group: 4 },
        { id: "PTX5", group: 4 },
        { id: "SSNS1", group: 1 },
        { id: "SSNS2", group: 1 },
        { id: "SSNS3", group: 1 },
        { id: "SSNS4", group: 1 },
        { id: "SSNS5", group: 1 },
        { id: "SSNS6", group: 1 },
        { id: "jvsp-calc-svc1", group: 2 },
        { id: "jvsp-calc-svc2", group: 2 },
        { id: "jvsp-calc-svc3", group: 2 },
        { id: "jvsp-calc-svc4", group: 2 },
        { id: "jvsp-calc-web1", group: 3 },
        { id: "jvsp-calc-web2", group: 3 },
        { id: "jvsp-calc-web3", group: 3 },
        { id: "jvsp-calc-web4", group: 3 },
        { id: "jvsp-calc-web5", group: 3 },
        { id: "jvsp-parms-svc1", group: 2 },
        { id: "jvsp-parms-svc2", group: 2 },
        { id: "jvsp-parms-svc3", group: 2 },
        { id: "jvsp-parms-svc4", group: 2 },
        { id: "jvsp-parms-web1", group: 3 },
        { id: "jvsp-parms-web2", group: 3 },
        { id: "jvsp-parms-web3", group: 3 },
        { id: "jvsp-parms-web4", group: 3 },
        { id: "jvsp-parms-web5", group: 3 },
        { id: "scs-supplies-admin1", group: 3 },
        { id: "scs-supplies-admin2", group: 3 },
        { id: "scs-supplies-admin3", group: 3 },
        { id: "scs-supplies-admin4", group: 3 },
        { id: "scs-supplies-admin5", group: 3 },
        { id: "scs-supplies-svc1", group: 2 },
        { id: "scs-supplies-svc2", group: 2 },
        { id: "scs-supplies-svc3", group: 2 },
        { id: "scs-supplies-svc4", group: 2 },
        { id: "scs-supplies-web1", group: 3 },
        { id: "scs-supplies-web2", group: 3 },
        { id: "scs-supplies-web3", group: 3 },
        { id: "scs-supplies-web4", group: 3 },
        { id: "scs-supplies-web5", group: 3 },
        



    ],

    links: [
        { source: "FPA1", target: "ACCOUNT3", value: 1 },
        { source: "FPA1", target: "ACTIVITY3", value: 1 },
        { source: "FPA1", target: "ACTIVITY5", value: 1 },
        { source: "FPA1", target: "ACTIVITY6", value: 1 },
        { source: "FPA1", target: "LEDGER5", value: 1 },
        { source: "FPA1", target: "LEDGER6", value: 1 },
        { source: "FPA1", target: "SSNS2", value: 1 },
        { source: "FPA1", target: "jvsp-calc-svc1", value: 1 },
        { source: "FPA1", target: "jvsp-calc-svc3", value: 1 },
        { source: "FPA1", target: "jvsp-calc-svc4", value: 1 },
        { source: "FPA1", target: "jvsp-parms-svc1", value: 1 },
        { source: "FPA1", target: "jvsp-parms-svc2", value: 1 },
        { source: "FPA1", target: "jvsp-parms-svc3", value: 1 },
        { source: "FPA1", target: "scs-supplies-svc3", value: 1 },
        { source: "FPA1", target: "scs-supplies-svc4", value: 1 },
        { source: "FPA2", target: "ACCOUNT1", value: 1 },
        { source: "FPA2", target: "ACCOUNT3", value: 1 },
        { source: "FPA2", target: "ACTIVITY3", value: 1 },
        { source: "FPA2", target: "ACTIVITY5", value: 1 },
        { source: "FPA2", target: "PEOPLE1", value: 1 },
        { source: "FPA2", target: "PROJECT3", value: 1 },
        { source: "FPA2", target: "SSNS3", value: 1 },
        { source: "FPA2", target: "SSNS6", value: 1 },
        { source: "FPA2", target: "jvsp-calc-svc1", value: 1 },
        { source: "FPA2", target: "jvsp-calc-svc3", value: 1 },
        { source: "FPA2", target: "jvsp-parms-svc1", value: 1 },
        { source: "FPA2", target: "jvsp-parms-svc2", value: 1 },
        { source: "FPA2", target: "jvsp-parms-svc4", value: 1 },
        { source: "FPA2", target: "scs-supplies-svc1", value: 1 },
        { source: "FPA2", target: "scs-supplies-svc2", value: 1 },
        { source: "FPA2", target: "scs-supplies-svc4", value: 1 },
        { source: "FPA3", target: "ACTIVITY5", value: 1 },
        { source: "FPA3", target: "ACTIVITY6", value: 1 },
        { source: "FPA3", target: "PEOPLE2", value: 1 },
        { source: "FPA3", target: "PROJECT6", value: 1 },
        { source: "FPA3", target: "SSNS1", value: 1 },
        { source: "FPA3", target: "jvsp-calc-svc1", value: 1 },
        { source: "FPA3", target: "jvsp-calc-svc3", value: 1 },
        { source: "FPA3", target: "jvsp-parms-svc1", value: 1 },
        { source: "FPA3", target: "jvsp-parms-svc4", value: 1 },
        { source: "FPA3", target: "scs-supplies-svc1", value: 1 },
        { source: "FPA3", target: "scs-supplies-svc3", value: 1 },
        { source: "FPA3", target: "scs-supplies-svc4", value: 1 },
        { source: "FPA4", target: "ACCOUNT1", value: 1 },
        { source: "FPA4", target: "ACCOUNT4", value: 1 },
        { source: "FPA4", target: "ACCOUNT6", value: 1 },
        { source: "FPA4", target: "ACTIVITY2", value: 1 },
        { source: "FPA4", target: "ACTIVITY5", value: 1 },
        { source: "FPA4", target: "LEDGER6", value: 1 },
        { source: "FPA4", target: "PEOPLE2", value: 1 },
        { source: "FPA4", target: "PEOPLE3", value: 1 },
        { source: "FPA4", target: "PROJECT1", value: 1 },
        { source: "FPA4", target: "PROJECT4", value: 1 },
        { source: "FPA4", target: "jvsp-calc-svc1", value: 1 },
        { source: "FPA4", target: "jvsp-calc-svc3", value: 1 },
        { source: "FPA4", target: "jvsp-parms-svc1", value: 1 },
        { source: "FPA4", target: "scs-supplies-svc1", value: 1 },
        { source: "FPA5", target: "ACCOUNT2", value: 1 },
        { source: "FPA5", target: "ACCOUNT4", value: 1 },
        { source: "FPA5", target: "ACTIVITY2", value: 1 },
        { source: "FPA5", target: "LEDGER1", value: 1 },
        { source: "FPA5", target: "PEOPLE5", value: 1 },
        { source: "FPA5", target: "PROJECT6", value: 1 },
        { source: "FPA5", target: "SSNS1", value: 1 },
        { source: "FPA5", target: "jvsp-calc-svc1", value: 1 },
        { source: "FPA5", target: "jvsp-calc-svc3", value: 1 },
        { source: "FPA5", target: "jvsp-calc-svc4", value: 1 },
        { source: "FPA5", target: "jvsp-parms-svc1", value: 1 },
        { source: "FPA5", target: "jvsp-parms-svc2", value: 1 },
        { source: "FPA5", target: "jvsp-parms-svc3", value: 1 },
        { source: "FPA5", target: "jvsp-parms-svc4", value: 1 },
        { source: "FPA5", target: "scs-supplies-svc2", value: 1 },
        { source: "FPA5", target: "scs-supplies-svc3", value: 1 },
        { source: "ICP1", target: "LEDGER6", value: 1 },
        { source: "ICP1", target: "PEOPLE3", value: 1 },
        { source: "ICP1", target: "PROJECT1", value: 1 },
        { source: "ICP1", target: "PROJECT2", value: 1 },
        { source: "ICP1", target: "jvsp-calc-svc2", value: 1 },
        { source: "ICP1", target: "jvsp-calc-svc3", value: 1 },
        { source: "ICP1", target: "jvsp-parms-svc2", value: 1 },
        { source: "ICP1", target: "jvsp-parms-svc3", value: 1 },
        { source: "ICP1", target: "scs-supplies-svc2", value: 1 },
        { source: "ICP1", target: "scs-supplies-svc4", value: 1 },
        { source: "ICP2", target: "ACCOUNT3", value: 1 },
        { source: "ICP2", target: "ACTIVITY4", value: 1 },
        { source: "ICP2", target: "ACTIVITY5", value: 1 },
        { source: "ICP2", target: "LEDGER4", value: 1 },
        { source: "ICP2", target: "LEDGER5", value: 1 },
        { source: "ICP2", target: "LEDGER6", value: 1 },
        { source: "ICP2", target: "PEOPLE5", value: 1 },
        { source: "ICP2", target: "SSNS4", value: 1 },
        { source: "ICP2", target: "jvsp-calc-svc1", value: 1 },
        { source: "ICP2", target: "jvsp-calc-svc3", value: 1 },
        { source: "ICP2", target: "jvsp-parms-svc2", value: 1 },
        { source: "ICP2", target: "jvsp-parms-svc4", value: 1 },
        { source: "ICP2", target: "scs-supplies-svc1", value: 1 },
        { source: "ICP2", target: "scs-supplies-svc2", value: 1 },
        { source: "ICP2", target: "scs-supplies-svc3", value: 1 },
        { source: "ICP2", target: "scs-supplies-svc4", value: 1 },
        { source: "ICP3", target: "ACTIVITY4", value: 1 },
        { source: "ICP3", target: "LEDGER4", value: 1 },
        { source: "ICP3", target: "LEDGER5", value: 1 },
        { source: "ICP3", target: "LEDGER6", value: 1 },
        { source: "ICP3", target: "PROJECT3", value: 1 },
        { source: "ICP3", target: "SSNS1", value: 1 },
        { source: "ICP3", target: "SSNS5", value: 1 },
        { source: "ICP3", target: "jvsp-calc-svc2", value: 1 },
        { source: "ICP3", target: "jvsp-parms-svc1", value: 1 },
        { source: "ICP3", target: "jvsp-parms-svc2", value: 1 },
        { source: "ICP3", target: "jvsp-parms-svc3", value: 1 },
        { source: "ICP3", target: "scs-supplies-svc1", value: 1 },
        { source: "ICP4", target: "ACCOUNT3", value: 1 },
        { source: "ICP4", target: "ACCOUNT4", value: 1 },
        { source: "ICP4", target: "ACCOUNT6", value: 1 },
        { source: "ICP4", target: "ACTIVITY1", value: 1 },
        { source: "ICP4", target: "ACTIVITY4", value: 1 },
        { source: "ICP4", target: "PEOPLE2", value: 1 },
        { source: "ICP4", target: "PROJECT5", value: 1 },
        { source: "ICP4", target: "SSNS6", value: 1 },
        { source: "ICP4", target: "jvsp-calc-svc3", value: 1 },
        { source: "ICP4", target: "jvsp-calc-svc4", value: 1 },
        { source: "ICP4", target: "jvsp-parms-svc2", value: 1 },
        { source: "ICP4", target: "jvsp-parms-svc3", value: 1 },
        { source: "ICP4", target: "scs-supplies-svc1", value: 1 },
        { source: "ICP5", target: "ACCOUNT3", value: 1 },
        { source: "ICP5", target: "ACCOUNT6", value: 1 },
        { source: "ICP5", target: "ACTIVITY4", value: 1 },
        { source: "ICP5", target: "ACTIVITY6", value: 1 },
        { source: "ICP5", target: "LEDGER5", value: 1 },
        { source: "ICP5", target: "PEOPLE2", value: 1 },
        { source: "ICP5", target: "PEOPLE4", value: 1 },
        { source: "ICP5", target: "PEOPLE5", value: 1 },
        { source: "ICP5", target: "PEOPLE6", value: 1 },
        { source: "ICP5", target: "PROJECT5", value: 1 },
        { source: "ICP5", target: "jvsp-calc-svc1", value: 1 },
        { source: "ICP5", target: "jvsp-calc-svc3", value: 1 },
        { source: "ICP5", target: "jvsp-parms-svc1", value: 1 },
        { source: "ICP5", target: "jvsp-parms-svc3", value: 1 },
        { source: "ICP5", target: "jvsp-parms-svc4", value: 1 },
        { source: "ICP5", target: "scs-supplies-svc1", value: 1 },
        { source: "ICP5", target: "scs-supplies-svc3", value: 1 },
        { source: "PSA1", target: "ACCOUNT2", value: 1 },
        { source: "PSA1", target: "ACCOUNT4", value: 1 },
        { source: "PSA1", target: "ACCOUNT5", value: 1 },
        { source: "PSA1", target: "ACTIVITY2", value: 1 },
        { source: "PSA1", target: "ACTIVITY4", value: 1 },
        { source: "PSA1", target: "LEDGER1", value: 1 },
        { source: "PSA1", target: "LEDGER6", value: 1 },
        { source: "PSA1", target: "PEOPLE4", value: 1 },
        { source: "PSA1", target: "PEOPLE5", value: 1 },
        { source: "PSA1", target: "PROJECT5", value: 1 },
        { source: "PSA1", target: "SSNS3", value: 1 },
        { source: "PSA1", target: "SSNS4", value: 1 },
        { source: "PSA1", target: "SSNS6", value: 1 },
        { source: "PSA1", target: "jvsp-calc-svc2", value: 1 },
        { source: "PSA1", target: "jvsp-calc-svc3", value: 1 },
        { source: "PSA1", target: "jvsp-calc-svc4", value: 1 },
        { source: "PSA1", target: "jvsp-parms-svc1", value: 1 },
        { source: "PSA1", target: "jvsp-parms-svc2", value: 1 },
        { source: "PSA1", target: "jvsp-parms-svc3", value: 1 },
        { source: "PSA1", target: "jvsp-parms-svc4", value: 1 },
        { source: "PSA1", target: "scs-supplies-svc1", value: 1 },
        { source: "PSA1", target: "scs-supplies-svc3", value: 1 },
        { source: "PSA1", target: "scs-supplies-svc4", value: 1 },
        { source: "PSA2", target: "ACTIVITY6", value: 1 },
        { source: "PSA2", target: "LEDGER3", value: 1 },
        { source: "PSA2", target: "PEOPLE2", value: 1 },
        { source: "PSA2", target: "PEOPLE4", value: 1 },
        { source: "PSA2", target: "PEOPLE5", value: 1 },
        { source: "PSA2", target: "PEOPLE6", value: 1 },
        { source: "PSA2", target: "jvsp-calc-svc1", value: 1 },
        { source: "PSA2", target: "jvsp-calc-svc4", value: 1 },
        { source: "PSA2", target: "jvsp-parms-svc1", value: 1 },
        { source: "PSA2", target: "jvsp-parms-svc2", value: 1 },
        { source: "PSA2", target: "jvsp-parms-svc3", value: 1 },
        { source: "PSA2", target: "scs-supplies-svc1", value: 1 },
        { source: "PSA2", target: "scs-supplies-svc3", value: 1 },
        { source: "PSA3", target: "ACCOUNT1", value: 1 },
        { source: "PSA3", target: "ACCOUNT6", value: 1 },
        { source: "PSA3", target: "ACTIVITY1", value: 1 },
        { source: "PSA3", target: "ACTIVITY3", value: 1 },
        { source: "PSA3", target: "ACTIVITY5", value: 1 },
        { source: "PSA3", target: "LEDGER5", value: 1 },
        { source: "PSA3", target: "PEOPLE6", value: 1 },
        { source: "PSA3", target: "PROJECT2", value: 1 },
        { source: "PSA3", target: "SSNS1", value: 1 },
        { source: "PSA3", target: "SSNS3", value: 1 },
        { source: "PSA3", target: "jvsp-calc-svc1", value: 1 },
        { source: "PSA3", target: "jvsp-calc-svc2", value: 1 },
        { source: "PSA3", target: "jvsp-calc-svc4", value: 1 },
        { source: "PSA3", target: "jvsp-parms-svc2", value: 1 },
        { source: "PSA3", target: "jvsp-parms-svc3", value: 1 },
        { source: "PSA3", target: "jvsp-parms-svc4", value: 1 },
        { source: "PSA3", target: "scs-supplies-svc1", value: 1 },
        { source: "PSA4", target: "ACCOUNT3", value: 1 },
        { source: "PSA4", target: "ACCOUNT6", value: 1 },
        { source: "PSA4", target: "ACTIVITY3", value: 1 },
        { source: "PSA4", target: "ACTIVITY4", value: 1 },
        { source: "PSA4", target: "LEDGER2", value: 1 },
        { source: "PSA4", target: "LEDGER6", value: 1 },
        { source: "PSA4", target: "PEOPLE4", value: 1 },
        { source: "PSA4", target: "PEOPLE6", value: 1 },
        { source: "PSA4", target: "PROJECT3", value: 1 },
        { source: "PSA4", target: "SSNS4", value: 1 },
        { source: "PSA4", target: "SSNS5", value: 1 },
        { source: "PSA4", target: "jvsp-calc-svc4", value: 1 },
        { source: "PSA4", target: "jvsp-parms-svc3", value: 1 },
        { source: "PSA4", target: "scs-supplies-svc1", value: 1 },
        { source: "PSA4", target: "scs-supplies-svc2", value: 1 },
        { source: "PSA4", target: "scs-supplies-svc3", value: 1 },
        { source: "PSA4", target: "scs-supplies-svc4", value: 1 },
        { source: "PSA5", target: "ACCOUNT3", value: 1 },
        { source: "PSA5", target: "ACCOUNT4", value: 1 },
        { source: "PSA5", target: "ACCOUNT6", value: 1 },
        { source: "PSA5", target: "ACTIVITY5", value: 1 },
        { source: "PSA5", target: "LEDGER5", value: 1 },
        { source: "PSA5", target: "PEOPLE2", value: 1 },
        { source: "PSA5", target: "PEOPLE4", value: 1 },
        { source: "PSA5", target: "PEOPLE5", value: 1 },
        { source: "PSA5", target: "PROJECT6", value: 1 },
        { source: "PSA5", target: "SSNS4", value: 1 },
        { source: "PSA5", target: "jvsp-calc-svc1", value: 1 },
        { source: "PSA5", target: "jvsp-calc-svc2", value: 1 },
        { source: "PSA5", target: "jvsp-calc-svc3", value: 1 },
        { source: "PSA5", target: "jvsp-parms-svc2", value: 1 },
        { source: "PSA5", target: "scs-supplies-svc2", value: 1 },
        { source: "PSA5", target: "scs-supplies-svc3", value: 1 },
        { source: "PSA5", target: "scs-supplies-svc4", value: 1 },
        { source: "PTX1", target: "ACCOUNT1", value: 1 },
        { source: "PTX1", target: "ACCOUNT3", value: 1 },
        { source: "PTX1", target: "ACTIVITY1", value: 1 },
        { source: "PTX1", target: "ACTIVITY2", value: 1 },
        { source: "PTX1", target: "ACTIVITY4", value: 1 },
        { source: "PTX1", target: "PEOPLE3", value: 1 },
        { source: "PTX1", target: "PROJECT3", value: 1 },
        { source: "PTX1", target: "PROJECT6", value: 1 },
        { source: "PTX1", target: "SSNS1", value: 1 },
        { source: "PTX1", target: "jvsp-calc-svc2", value: 1 },
        { source: "PTX1", target: "jvsp-calc-svc3", value: 1 },
        { source: "PTX1", target: "jvsp-parms-svc2", value: 1 },
        { source: "PTX1", target: "jvsp-parms-svc4", value: 1 },
        { source: "PTX1", target: "scs-supplies-svc4", value: 1 },
        { source: "PTX2", target: "ACCOUNT1", value: 1 },
        { source: "PTX2", target: "ACCOUNT3", value: 1 },
        { source: "PTX2", target: "ACCOUNT4", value: 1 },
        { source: "PTX2", target: "ACTIVITY3", value: 1 },
        { source: "PTX2", target: "ACTIVITY4", value: 1 },
        { source: "PTX2", target: "PEOPLE5", value: 1 },
        { source: "PTX2", target: "PROJECT2", value: 1 },
        { source: "PTX2", target: "SSNS3", value: 1 },
        { source: "PTX2", target: "SSNS5", value: 1 },
        { source: "PTX2", target: "jvsp-calc-svc1", value: 1 },
        { source: "PTX2", target: "jvsp-calc-svc2", value: 1 },
        { source: "PTX2", target: "jvsp-calc-svc3", value: 1 },
        { source: "PTX2", target: "jvsp-calc-svc4", value: 1 },
        { source: "PTX2", target: "jvsp-parms-svc2", value: 1 },
        { source: "PTX2", target: "jvsp-parms-svc3", value: 1 },
        { source: "PTX2", target: "scs-supplies-svc1", value: 1 },
        { source: "PTX2", target: "scs-supplies-svc2", value: 1 },
        { source: "PTX2", target: "scs-supplies-svc3", value: 1 },
        { source: "PTX3", target: "ACCOUNT2", value: 1 },
        { source: "PTX3", target: "ACCOUNT6", value: 1 },
        { source: "PTX3", target: "LEDGER6", value: 1 },
        { source: "PTX3", target: "PEOPLE2", value: 1 },
        { source: "PTX3", target: "PROJECT1", value: 1 },
        { source: "PTX3", target: "PROJECT2", value: 1 },
        { source: "PTX3", target: "SSNS2", value: 1 },
        { source: "PTX3", target: "SSNS3", value: 1 },
        { source: "PTX3", target: "jvsp-calc-svc1", value: 1 },
        { source: "PTX3", target: "jvsp-calc-svc4", value: 1 },
        { source: "PTX3", target: "jvsp-parms-svc1", value: 1 },
        { source: "PTX3", target: "jvsp-parms-svc2", value: 1 },
        { source: "PTX3", target: "jvsp-parms-svc3", value: 1 },
        { source: "PTX3", target: "jvsp-parms-svc4", value: 1 },
        { source: "PTX3", target: "scs-supplies-svc1", value: 1 },
        { source: "PTX4", target: "ACCOUNT2", value: 1 },
        { source: "PTX4", target: "ACCOUNT3", value: 1 },
        { source: "PTX4", target: "ACTIVITY1", value: 1 },
        { source: "PTX4", target: "LEDGER3", value: 1 },
        { source: "PTX4", target: "PEOPLE4", value: 1 },
        { source: "PTX4", target: "PROJECT2", value: 1 },
        { source: "PTX4", target: "PROJECT4", value: 1 },
        { source: "PTX4", target: "PROJECT5", value: 1 },
        { source: "PTX4", target: "SSNS4", value: 1 },
        { source: "PTX4", target: "SSNS5", value: 1 },
        { source: "PTX4", target: "SSNS6", value: 1 },
        { source: "PTX4", target: "scs-supplies-svc2", value: 1 },
        { source: "PTX5", target: "ACCOUNT1", value: 1 },
        { source: "PTX5", target: "ACCOUNT5", value: 1 },
        { source: "PTX5", target: "LEDGER1", value: 1 },
        { source: "PTX5", target: "PEOPLE3", value: 1 },
        { source: "PTX5", target: "PEOPLE4", value: 1 },
        { source: "PTX5", target: "PROJECT1", value: 1 },
        { source: "PTX5", target: "PROJECT6", value: 1 },
        { source: "PTX5", target: "SSNS1", value: 1 },
        { source: "PTX5", target: "SSNS2", value: 1 },
        { source: "PTX5", target: "SSNS5", value: 1 },
        { source: "PTX5", target: "SSNS6", value: 1 },
        { source: "PTX5", target: "jvsp-calc-svc2", value: 1 },
        { source: "PTX5", target: "jvsp-calc-svc3", value: 1 },
        { source: "PTX5", target: "jvsp-parms-svc1", value: 1 },
        { source: "PTX5", target: "jvsp-parms-svc4", value: 1 },
        { source: "PTX5", target: "scs-supplies-svc1", value: 1 },
        { source: "PTX5", target: "scs-supplies-svc2", value: 1 },
        { source: "PTX5", target: "scs-supplies-svc3", value: 1 },
        { source: "jvsp-calc-svc1", target: "ACCOUNT1", value: 1 },
        { source: "jvsp-calc-svc1", target: "ACCOUNT2", value: 1 },
        { source: "jvsp-calc-svc1", target: "ACCOUNT3", value: 1 },
        { source: "jvsp-calc-svc1", target: "ACTIVITY2", value: 1 },
        { source: "jvsp-calc-svc1", target: "LEDGER2", value: 1 },
        { source: "jvsp-calc-svc1", target: "LEDGER5", value: 1 },
        { source: "jvsp-calc-svc1", target: "PEOPLE1", value: 1 },
        { source: "jvsp-calc-svc1", target: "PEOPLE3", value: 1 },
        { source: "jvsp-calc-svc1", target: "PEOPLE5", value: 1 },
        { source: "jvsp-calc-svc1", target: "PROJECT2", value: 1 },
        { source: "jvsp-calc-svc1", target: "PROJECT5", value: 1 },
        { source: "jvsp-calc-svc1", target: "SSNS1", value: 1 },
        { source: "jvsp-calc-svc1", target: "SSNS6", value: 1 },
        { source: "jvsp-calc-svc1", target: "jvsp-calc-svc1", value: 1 },
        { source: "jvsp-calc-svc1", target: "jvsp-calc-svc2", value: 1 },
        { source: "jvsp-calc-svc1", target: "jvsp-calc-svc3", value: 1 },
        { source: "jvsp-calc-svc1", target: "jvsp-calc-svc4", value: 1 },
        { source: "jvsp-calc-svc1", target: "jvsp-parms-svc1", value: 1 },
        { source: "jvsp-calc-svc1", target: "jvsp-parms-svc2", value: 1 },
        { source: "jvsp-calc-svc1", target: "jvsp-parms-svc3", value: 1 },
        { source: "jvsp-calc-svc1", target: "jvsp-parms-svc4", value: 1 },
        { source: "jvsp-calc-svc1", target: "scs-supplies-svc1", value: 1 },
        { source: "jvsp-calc-svc1", target: "scs-supplies-svc3", value: 1 },
        { source: "jvsp-calc-svc1", target: "scs-supplies-svc4", value: 1 },
        { source: "jvsp-calc-svc2", target: "ACCOUNT1", value: 1 },
        { source: "jvsp-calc-svc2", target: "ACCOUNT2", value: 1 },
        { source: "jvsp-calc-svc2", target: "ACCOUNT5", value: 1 },
        { source: "jvsp-calc-svc2", target: "ACTIVITY2", value: 1 },
        { source: "jvsp-calc-svc2", target: "ACTIVITY5", value: 1 },
        { source: "jvsp-calc-svc2", target: "LEDGER1", value: 1 },
        { source: "jvsp-calc-svc2", target: "LEDGER3", value: 1 },
        { source: "jvsp-calc-svc2", target: "LEDGER4", value: 1 },
        { source: "jvsp-calc-svc2", target: "LEDGER6", value: 1 },
        { source: "jvsp-calc-svc2", target: "PEOPLE4", value: 1 },
        { source: "jvsp-calc-svc2", target: "PEOPLE5", value: 1 },
        { source: "jvsp-calc-svc2", target: "PEOPLE6", value: 1 },
        { source: "jvsp-calc-svc2", target: "PROJECT5", value: 1 },
        { source: "jvsp-calc-svc2", target: "SSNS1", value: 1 },
        { source: "jvsp-calc-svc2", target: "SSNS6", value: 1 },
        { source: "jvsp-calc-svc2", target: "jvsp-calc-svc1", value: 1 },
        { source: "jvsp-calc-svc2", target: "jvsp-calc-svc2", value: 1 },
        { source: "jvsp-calc-svc2", target: "jvsp-calc-svc3", value: 1 },
        { source: "jvsp-calc-svc2", target: "jvsp-parms-svc1", value: 1 },
        { source: "jvsp-calc-svc2", target: "jvsp-parms-svc2", value: 1 },
        { source: "jvsp-calc-svc2", target: "jvsp-parms-svc3", value: 1 },
        { source: "jvsp-calc-svc2", target: "scs-supplies-svc1", value: 1 },
        { source: "jvsp-calc-svc2", target: "scs-supplies-svc4", value: 1 },
        { source: "jvsp-calc-svc3", target: "ACCOUNT2", value: 1 },
        { source: "jvsp-calc-svc3", target: "ACTIVITY1", value: 1 },
        { source: "jvsp-calc-svc3", target: "ACTIVITY2", value: 1 },
        { source: "jvsp-calc-svc3", target: "LEDGER3", value: 1 },
        { source: "jvsp-calc-svc3", target: "LEDGER4", value: 1 },
        { source: "jvsp-calc-svc3", target: "LEDGER5", value: 1 },
        { source: "jvsp-calc-svc3", target: "PEOPLE3", value: 1 },
        { source: "jvsp-calc-svc3", target: "PROJECT2", value: 1 },
        { source: "jvsp-calc-svc3", target: "SSNS2", value: 1 },
        { source: "jvsp-calc-svc3", target: "SSNS3", value: 1 },
        { source: "jvsp-calc-svc3", target: "SSNS6", value: 1 },
        { source: "jvsp-calc-svc3", target: "jvsp-calc-svc1", value: 1 },
        { source: "jvsp-calc-svc3", target: "jvsp-parms-svc1", value: 1 },
        { source: "jvsp-calc-svc3", target: "jvsp-parms-svc2", value: 1 },
        { source: "jvsp-calc-svc3", target: "jvsp-parms-svc4", value: 1 },
        { source: "jvsp-calc-svc3", target: "scs-supplies-svc1", value: 1 },
        { source: "jvsp-calc-svc3", target: "scs-supplies-svc3", value: 1 },
        { source: "jvsp-calc-svc3", target: "scs-supplies-svc4", value: 1 },
        { source: "jvsp-calc-svc4", target: "ACCOUNT2", value: 1 },
        { source: "jvsp-calc-svc4", target: "ACCOUNT3", value: 1 },
        { source: "jvsp-calc-svc4", target: "ACCOUNT5", value: 1 },
        { source: "jvsp-calc-svc4", target: "ACTIVITY1", value: 1 },
        { source: "jvsp-calc-svc4", target: "ACTIVITY3", value: 1 },
        { source: "jvsp-calc-svc4", target: "ACTIVITY5", value: 1 },
        { source: "jvsp-calc-svc4", target: "LEDGER3", value: 1 },
        { source: "jvsp-calc-svc4", target: "LEDGER4", value: 1 },
        { source: "jvsp-calc-svc4", target: "LEDGER5", value: 1 },
        { source: "jvsp-calc-svc4", target: "PEOPLE2", value: 1 },
        { source: "jvsp-calc-svc4", target: "PEOPLE4", value: 1 },
        { source: "jvsp-calc-svc4", target: "PEOPLE5", value: 1 },
        { source: "jvsp-calc-svc4", target: "PROJECT1", value: 1 },
        { source: "jvsp-calc-svc4", target: "PROJECT3", value: 1 },
        { source: "jvsp-calc-svc4", target: "SSNS2", value: 1 },
        { source: "jvsp-calc-svc4", target: "SSNS4", value: 1 },
        { source: "jvsp-calc-svc4", target: "SSNS6", value: 1 },
        { source: "jvsp-calc-svc4", target: "jvsp-calc-svc1", value: 1 },
        { source: "jvsp-calc-svc4", target: "jvsp-calc-svc2", value: 1 },
        { source: "jvsp-calc-svc4", target: "jvsp-calc-svc4", value: 1 },
        { source: "jvsp-calc-svc4", target: "jvsp-parms-svc2", value: 1 },
        { source: "jvsp-calc-svc4", target: "jvsp-parms-svc3", value: 1 },
        { source: "jvsp-calc-svc4", target: "scs-supplies-svc2", value: 1 },
        { source: "jvsp-calc-svc4", target: "scs-supplies-svc3", value: 1 },
        { source: "jvsp-calc-web1", target: "jvsp-calc-svc2", value: 1 },
        { source: "jvsp-calc-web1", target: "jvsp-parms-svc2", value: 1 },
        { source: "jvsp-calc-web1", target: "jvsp-parms-svc3", value: 1 },
        { source: "jvsp-calc-web1", target: "jvsp-parms-svc4", value: 1 },
        { source: "jvsp-calc-web1", target: "scs-supplies-svc1", value: 1 },
        { source: "jvsp-calc-web1", target: "scs-supplies-svc3", value: 1 },
        { source: "jvsp-calc-web1", target: "scs-supplies-svc4", value: 1 },
        { source: "jvsp-calc-web2", target: "jvsp-calc-svc1", value: 1 },
        { source: "jvsp-calc-web2", target: "jvsp-calc-svc3", value: 1 },
        { source: "jvsp-calc-web2", target: "jvsp-parms-svc1", value: 1 },
        { source: "jvsp-calc-web2", target: "scs-supplies-svc1", value: 1 },
        { source: "jvsp-calc-web2", target: "scs-supplies-svc2", value: 1 },
        { source: "jvsp-calc-web2", target: "scs-supplies-svc3", value: 1 },
        { source: "jvsp-calc-web3", target: "jvsp-calc-svc1", value: 1 },
        { source: "jvsp-calc-web3", target: "jvsp-calc-svc4", value: 1 },
        { source: "jvsp-calc-web3", target: "jvsp-parms-svc1", value: 1 },
        { source: "jvsp-calc-web3", target: "jvsp-parms-svc2", value: 1 },
        { source: "jvsp-calc-web3", target: "jvsp-parms-svc3", value: 1 },
        { source: "jvsp-calc-web3", target: "scs-supplies-svc2", value: 1 },
        { source: "jvsp-calc-web3", target: "scs-supplies-svc3", value: 1 },
        { source: "jvsp-calc-web3", target: "scs-supplies-svc4", value: 1 },
        { source: "jvsp-calc-web4", target: "jvsp-calc-svc1", value: 1 },
        { source: "jvsp-calc-web4", target: "jvsp-calc-svc2", value: 1 },
        { source: "jvsp-calc-web4", target: "jvsp-calc-svc4", value: 1 },
        { source: "jvsp-calc-web4", target: "jvsp-parms-svc1", value: 1 },
        { source: "jvsp-calc-web4", target: "jvsp-parms-svc2", value: 1 },
        { source: "jvsp-calc-web4", target: "jvsp-parms-svc3", value: 1 },
        { source: "jvsp-calc-web4", target: "jvsp-parms-svc4", value: 1 },
        { source: "jvsp-calc-web4", target: "scs-supplies-svc2", value: 1 },
        { source: "jvsp-calc-web4", target: "scs-supplies-svc4", value: 1 },
        { source: "jvsp-calc-web5", target: "jvsp-calc-svc3", value: 1 },
        { source: "jvsp-calc-web5", target: "jvsp-calc-svc4", value: 1 },
        { source: "jvsp-calc-web5", target: "jvsp-parms-svc2", value: 1 },
        { source: "jvsp-calc-web5", target: "jvsp-parms-svc3", value: 1 },
        { source: "jvsp-calc-web5", target: "scs-supplies-svc3", value: 1 },
        { source: "jvsp-parms-svc1", target: "ACCOUNT1", value: 1 },
        { source: "jvsp-parms-svc1", target: "ACCOUNT4", value: 1 },
        { source: "jvsp-parms-svc1", target: "ACCOUNT5", value: 1 },
        { source: "jvsp-parms-svc1", target: "ACTIVITY2", value: 1 },
        { source: "jvsp-parms-svc1", target: "ACTIVITY3", value: 1 },
        { source: "jvsp-parms-svc1", target: "ACTIVITY5", value: 1 },
        { source: "jvsp-parms-svc1", target: "ACTIVITY6", value: 1 },
        { source: "jvsp-parms-svc1", target: "LEDGER1", value: 1 },
        { source: "jvsp-parms-svc1", target: "LEDGER5", value: 1 },
        { source: "jvsp-parms-svc1", target: "PEOPLE2", value: 1 },
        { source: "jvsp-parms-svc1", target: "PEOPLE3", value: 1 },
        { source: "jvsp-parms-svc1", target: "PROJECT6", value: 1 },
        { source: "jvsp-parms-svc1", target: "SSNS2", value: 1 },
        { source: "jvsp-parms-svc1", target: "SSNS4", value: 1 },
        { source: "jvsp-parms-svc1", target: "SSNS6", value: 1 },
        { source: "jvsp-parms-svc1", target: "jvsp-calc-svc1", value: 1 },
        { source: "jvsp-parms-svc1", target: "jvsp-calc-svc2", value: 1 },
        { source: "jvsp-parms-svc1", target: "jvsp-calc-svc4", value: 1 },
        { source: "jvsp-parms-svc1", target: "jvsp-parms-svc1", value: 1 },
        { source: "jvsp-parms-svc1", target: "jvsp-parms-svc3", value: 1 },
        { source: "jvsp-parms-svc1", target: "jvsp-parms-svc4", value: 1 },
        { source: "jvsp-parms-svc1", target: "scs-supplies-svc1", value: 1 },
        { source: "jvsp-parms-svc1", target: "scs-supplies-svc2", value: 1 },
        { source: "jvsp-parms-svc1", target: "scs-supplies-svc3", value: 1 },
        { source: "jvsp-parms-svc1", target: "scs-supplies-svc4", value: 1 },
        { source: "jvsp-parms-svc2", target: "ACCOUNT1", value: 1 },
        { source: "jvsp-parms-svc2", target: "ACCOUNT2", value: 1 },
        { source: "jvsp-parms-svc2", target: "ACCOUNT4", value: 1 },
        { source: "jvsp-parms-svc2", target: "ACCOUNT5", value: 1 },
        { source: "jvsp-parms-svc2", target: "ACCOUNT6", value: 1 },
        { source: "jvsp-parms-svc2", target: "ACTIVITY1", value: 1 },
        { source: "jvsp-parms-svc2", target: "ACTIVITY4", value: 1 },
        { source: "jvsp-parms-svc2", target: "ACTIVITY5", value: 1 },
        { source: "jvsp-parms-svc2", target: "LEDGER1", value: 1 },
        { source: "jvsp-parms-svc2", target: "LEDGER3", value: 1 },
        { source: "jvsp-parms-svc2", target: "LEDGER5", value: 1 },
        { source: "jvsp-parms-svc2", target: "PEOPLE2", value: 1 },
        { source: "jvsp-parms-svc2", target: "PEOPLE3", value: 1 },
        { source: "jvsp-parms-svc2", target: "PEOPLE5", value: 1 },
        { source: "jvsp-parms-svc2", target: "PEOPLE6", value: 1 },
        { source: "jvsp-parms-svc2", target: "PROJECT1", value: 1 },
        { source: "jvsp-parms-svc2", target: "PROJECT3", value: 1 },
        { source: "jvsp-parms-svc2", target: "PROJECT5", value: 1 },
        { source: "jvsp-parms-svc2", target: "PROJECT6", value: 1 },
        { source: "jvsp-parms-svc2", target: "SSNS2", value: 1 },
        { source: "jvsp-parms-svc2", target: "SSNS4", value: 1 },
        { source: "jvsp-parms-svc2", target: "jvsp-calc-svc1", value: 1 },
        { source: "jvsp-parms-svc2", target: "jvsp-calc-svc2", value: 1 },
        { source: "jvsp-parms-svc2", target: "jvsp-calc-svc3", value: 1 },
        { source: "jvsp-parms-svc2", target: "jvsp-calc-svc4", value: 1 },
        { source: "jvsp-parms-svc2", target: "jvsp-parms-svc1", value: 1 },
        { source: "jvsp-parms-svc2", target: "jvsp-parms-svc2", value: 1 },
        { source: "jvsp-parms-svc2", target: "jvsp-parms-svc3", value: 1 },
        { source: "jvsp-parms-svc2", target: "jvsp-parms-svc4", value: 1 },
        { source: "jvsp-parms-svc2", target: "scs-supplies-svc4", value: 1 },
        { source: "jvsp-parms-svc3", target: "ACCOUNT3", value: 1 },
        { source: "jvsp-parms-svc3", target: "ACCOUNT4", value: 1 },
        { source: "jvsp-parms-svc3", target: "ACCOUNT6", value: 1 },
        { source: "jvsp-parms-svc3", target: "ACTIVITY5", value: 1 },
        { source: "jvsp-parms-svc3", target: "LEDGER4", value: 1 },
        { source: "jvsp-parms-svc3", target: "PEOPLE2", value: 1 },
        { source: "jvsp-parms-svc3", target: "PEOPLE3", value: 1 },
        { source: "jvsp-parms-svc3", target: "PEOPLE5", value: 1 },
        { source: "jvsp-parms-svc3", target: "PEOPLE6", value: 1 },
        { source: "jvsp-parms-svc3", target: "PROJECT2", value: 1 },
        { source: "jvsp-parms-svc3", target: "PROJECT3", value: 1 },
        { source: "jvsp-parms-svc3", target: "PROJECT6", value: 1 },
        { source: "jvsp-parms-svc3", target: "SSNS2", value: 1 },
        { source: "jvsp-parms-svc3", target: "SSNS4", value: 1 },
        { source: "jvsp-parms-svc3", target: "jvsp-calc-svc2", value: 1 },
        { source: "jvsp-parms-svc3", target: "jvsp-calc-svc3", value: 1 },
        { source: "jvsp-parms-svc3", target: "jvsp-calc-svc4", value: 1 },
        { source: "jvsp-parms-svc3", target: "jvsp-parms-svc1", value: 1 },
        { source: "jvsp-parms-svc3", target: "jvsp-parms-svc3", value: 1 },
        { source: "jvsp-parms-svc3", target: "jvsp-parms-svc4", value: 1 },
        { source: "jvsp-parms-svc3", target: "scs-supplies-svc1", value: 1 },
        { source: "jvsp-parms-svc3", target: "scs-supplies-svc2", value: 1 },
        { source: "jvsp-parms-svc3", target: "scs-supplies-svc3", value: 1 },
        { source: "jvsp-parms-svc3", target: "scs-supplies-svc4", value: 1 },
        { source: "jvsp-parms-svc4", target: "ACCOUNT1", value: 1 },
        { source: "jvsp-parms-svc4", target: "ACCOUNT2", value: 1 },
        { source: "jvsp-parms-svc4", target: "ACCOUNT4", value: 1 },
        { source: "jvsp-parms-svc4", target: "ACCOUNT5", value: 1 },
        { source: "jvsp-parms-svc4", target: "ACCOUNT6", value: 1 },
        { source: "jvsp-parms-svc4", target: "ACTIVITY2", value: 1 },
        { source: "jvsp-parms-svc4", target: "ACTIVITY5", value: 1 },
        { source: "jvsp-parms-svc4", target: "LEDGER3", value: 1 },
        { source: "jvsp-parms-svc4", target: "LEDGER6", value: 1 },
        { source: "jvsp-parms-svc4", target: "PEOPLE5", value: 1 },
        { source: "jvsp-parms-svc4", target: "PROJECT2", value: 1 },
        { source: "jvsp-parms-svc4", target: "PROJECT3", value: 1 },
        { source: "jvsp-parms-svc4", target: "PROJECT4", value: 1 },
        { source: "jvsp-parms-svc4", target: "SSNS3", value: 1 },
        { source: "jvsp-parms-svc4", target: "SSNS5", value: 1 },
        { source: "jvsp-parms-svc4", target: "SSNS6", value: 1 },
        { source: "jvsp-parms-svc4", target: "jvsp-calc-svc1", value: 1 },
        { source: "jvsp-parms-svc4", target: "jvsp-calc-svc3", value: 1 },
        { source: "jvsp-parms-svc4", target: "jvsp-calc-svc4", value: 1 },
        { source: "jvsp-parms-svc4", target: "jvsp-parms-svc1", value: 1 },
        { source: "jvsp-parms-svc4", target: "jvsp-parms-svc2", value: 1 },
        { source: "jvsp-parms-svc4", target: "jvsp-parms-svc3", value: 1 },
        { source: "jvsp-parms-svc4", target: "jvsp-parms-svc4", value: 1 },
        { source: "jvsp-parms-svc4", target: "scs-supplies-svc1", value: 1 },
        { source: "jvsp-parms-svc4", target: "scs-supplies-svc2", value: 1 },
        { source: "jvsp-parms-svc4", target: "scs-supplies-svc3", value: 1 },
        { source: "jvsp-parms-svc4", target: "scs-supplies-svc4", value: 1 },
        { source: "jvsp-parms-web1", target: "jvsp-calc-svc2", value: 1 },
        { source: "jvsp-parms-web1", target: "jvsp-parms-svc3", value: 1 },
        { source: "jvsp-parms-web1", target: "scs-supplies-svc1", value: 1 },
        { source: "jvsp-parms-web1", target: "scs-supplies-svc2", value: 1 },
        { source: "jvsp-parms-web1", target: "scs-supplies-svc3", value: 1 },
        { source: "jvsp-parms-web1", target: "scs-supplies-svc4", value: 1 },
        { source: "jvsp-parms-web2", target: "jvsp-calc-svc1", value: 1 },
        { source: "jvsp-parms-web2", target: "jvsp-calc-svc3", value: 1 },
        { source: "jvsp-parms-web2", target: "scs-supplies-svc1", value: 1 },
        { source: "jvsp-parms-web2", target: "scs-supplies-svc2", value: 1 },
        { source: "jvsp-parms-web2", target: "scs-supplies-svc3", value: 1 },
        { source: "jvsp-parms-web2", target: "scs-supplies-svc4", value: 1 },
        { source: "jvsp-parms-web3", target: "jvsp-calc-svc2", value: 1 },
        { source: "jvsp-parms-web3", target: "jvsp-calc-svc4", value: 1 },
        { source: "jvsp-parms-web3", target: "jvsp-parms-svc1", value: 1 },
        { source: "jvsp-parms-web3", target: "jvsp-parms-svc2", value: 1 },
        { source: "jvsp-parms-web3", target: "jvsp-parms-svc3", value: 1 },
        { source: "jvsp-parms-web3", target: "jvsp-parms-svc4", value: 1 },
        { source: "jvsp-parms-web3", target: "scs-supplies-svc1", value: 1 },
        { source: "jvsp-parms-web3", target: "scs-supplies-svc4", value: 1 },
        { source: "jvsp-parms-web4", target: "jvsp-calc-svc1", value: 1 },
        { source: "jvsp-parms-web4", target: "jvsp-calc-svc2", value: 1 },
        { source: "jvsp-parms-web4", target: "jvsp-parms-svc1", value: 1 },
        { source: "jvsp-parms-web4", target: "jvsp-parms-svc2", value: 1 },
        { source: "jvsp-parms-web4", target: "jvsp-parms-svc3", value: 1 },
        { source: "jvsp-parms-web4", target: "jvsp-parms-svc4", value: 1 },
        { source: "jvsp-parms-web4", target: "scs-supplies-svc1", value: 1 },
        { source: "jvsp-parms-web4", target: "scs-supplies-svc2", value: 1 },
        { source: "jvsp-parms-web4", target: "scs-supplies-svc3", value: 1 },
        { source: "jvsp-parms-web5", target: "jvsp-calc-svc1", value: 1 },
        { source: "jvsp-parms-web5", target: "jvsp-calc-svc2", value: 1 },
        { source: "jvsp-parms-web5", target: "jvsp-calc-svc3", value: 1 },
        { source: "jvsp-parms-web5", target: "jvsp-parms-svc2", value: 1 },
        { source: "jvsp-parms-web5", target: "jvsp-parms-svc3", value: 1 },
        { source: "jvsp-parms-web5", target: "scs-supplies-svc1", value: 1 },
        { source: "jvsp-parms-web5", target: "scs-supplies-svc3", value: 1 },
        { source: "jvsp-parms-web5", target: "scs-supplies-svc4", value: 1 },
        { source: "scs-supplies-admin1", target: "jvsp-calc-svc1", value: 1 },
        { source: "scs-supplies-admin1", target: "jvsp-calc-svc2", value: 1 },
        { source: "scs-supplies-admin1", target: "jvsp-parms-svc2", value: 1 },
        { source: "scs-supplies-admin1", target: "jvsp-parms-svc4", value: 1 },
        { source: "scs-supplies-admin1", target: "scs-supplies-svc4", value: 1 },
        { source: "scs-supplies-admin2", target: "jvsp-calc-svc2", value: 1 },
        { source: "scs-supplies-admin2", target: "jvsp-calc-svc4", value: 1 },
        { source: "scs-supplies-admin2", target: "jvsp-parms-svc1", value: 1 },
        { source: "scs-supplies-admin2", target: "jvsp-parms-svc3", value: 1 },
        { source: "scs-supplies-admin2", target: "scs-supplies-svc4", value: 1 },
        { source: "scs-supplies-admin3", target: "jvsp-parms-svc2", value: 1 },
        { source: "scs-supplies-admin3", target: "jvsp-parms-svc3", value: 1 },
        { source: "scs-supplies-admin3", target: "jvsp-parms-svc4", value: 1 },
        { source: "scs-supplies-admin3", target: "scs-supplies-svc3", value: 1 },
        { source: "scs-supplies-admin4", target: "jvsp-calc-svc4", value: 1 },
        { source: "scs-supplies-admin4", target: "jvsp-parms-svc1", value: 1 },
        { source: "scs-supplies-admin4", target: "jvsp-parms-svc4", value: 1 },
        { source: "scs-supplies-admin4", target: "scs-supplies-svc2", value: 1 },
        { source: "scs-supplies-admin4", target: "scs-supplies-svc3", value: 1 },
        { source: "scs-supplies-admin5", target: "jvsp-calc-svc4", value: 1 },
        { source: "scs-supplies-admin5", target: "jvsp-parms-svc1", value: 1 },
        { source: "scs-supplies-admin5", target: "jvsp-parms-svc3", value: 1 },
        { source: "scs-supplies-admin5", target: "jvsp-parms-svc4", value: 1 },
        { source: "scs-supplies-admin5", target: "scs-supplies-svc1", value: 1 },
        { source: "scs-supplies-admin5", target: "scs-supplies-svc2", value: 1 },
        { source: "scs-supplies-admin5", target: "scs-supplies-svc3", value: 1 },
        { source: "scs-supplies-admin5", target: "scs-supplies-svc4", value: 1 },
        { source: "scs-supplies-svc1", target: "ACCOUNT1", value: 1 },
        { source: "scs-supplies-svc1", target: "ACCOUNT5", value: 1 },
        { source: "scs-supplies-svc1", target: "ACTIVITY4", value: 1 },
        { source: "scs-supplies-svc1", target: "LEDGER4", value: 1 },
        { source: "scs-supplies-svc1", target: "LEDGER6", value: 1 },
        { source: "scs-supplies-svc1", target: "PEOPLE1", value: 1 },
        { source: "scs-supplies-svc1", target: "PROJECT1", value: 1 },
        { source: "scs-supplies-svc1", target: "PROJECT2", value: 1 },
        { source: "scs-supplies-svc1", target: "PROJECT6", value: 1 },
        { source: "scs-supplies-svc1", target: "SSNS2", value: 1 },
        { source: "scs-supplies-svc1", target: "jvsp-calc-svc1", value: 1 },
        { source: "scs-supplies-svc1", target: "jvsp-calc-svc2", value: 1 },
        { source: "scs-supplies-svc1", target: "jvsp-calc-svc3", value: 1 },
        { source: "scs-supplies-svc1", target: "jvsp-calc-svc4", value: 1 },
        { source: "scs-supplies-svc1", target: "jvsp-parms-svc1", value: 1 },
        { source: "scs-supplies-svc1", target: "jvsp-parms-svc2", value: 1 },
        { source: "scs-supplies-svc1", target: "jvsp-parms-svc3", value: 1 },
        { source: "scs-supplies-svc1", target: "jvsp-parms-svc4", value: 1 },
        { source: "scs-supplies-svc1", target: "scs-supplies-svc1", value: 1 },
        { source: "scs-supplies-svc1", target: "scs-supplies-svc2", value: 1 },
        { source: "scs-supplies-svc1", target: "scs-supplies-svc3", value: 1 },
        { source: "scs-supplies-svc1", target: "scs-supplies-svc4", value: 1 },
        { source: "scs-supplies-svc2", target: "ACCOUNT1", value: 1 },
        { source: "scs-supplies-svc2", target: "ACCOUNT2", value: 1 },
        { source: "scs-supplies-svc2", target: "ACCOUNT4", value: 1 },
        { source: "scs-supplies-svc2", target: "ACCOUNT5", value: 1 },
        { source: "scs-supplies-svc2", target: "ACTIVITY5", value: 1 },
        { source: "scs-supplies-svc2", target: "PEOPLE4", value: 1 },
        { source: "scs-supplies-svc2", target: "PROJECT2", value: 1 },
        { source: "scs-supplies-svc2", target: "PROJECT5", value: 1 },
        { source: "scs-supplies-svc2", target: "SSNS4", value: 1 },
        { source: "scs-supplies-svc2", target: "SSNS5", value: 1 },
        { source: "scs-supplies-svc2", target: "SSNS6", value: 1 },
        { source: "scs-supplies-svc2", target: "jvsp-calc-svc1", value: 1 },
        { source: "scs-supplies-svc2", target: "jvsp-calc-svc4", value: 1 },
        { source: "scs-supplies-svc2", target: "jvsp-parms-svc1", value: 1 },
        { source: "scs-supplies-svc2", target: "jvsp-parms-svc2", value: 1 },
        { source: "scs-supplies-svc2", target: "jvsp-parms-svc3", value: 1 },
        { source: "scs-supplies-svc2", target: "jvsp-parms-svc4", value: 1 },
        { source: "scs-supplies-svc2", target: "scs-supplies-svc2", value: 1 },
        { source: "scs-supplies-svc2", target: "scs-supplies-svc3", value: 1 },
        { source: "scs-supplies-svc2", target: "scs-supplies-svc4", value: 1 },
        { source: "scs-supplies-svc3", target: "ACCOUNT4", value: 1 },
        { source: "scs-supplies-svc3", target: "ACTIVITY1", value: 1 },
        { source: "scs-supplies-svc3", target: "ACTIVITY2", value: 1 },
        { source: "scs-supplies-svc3", target: "ACTIVITY3", value: 1 },
        { source: "scs-supplies-svc3", target: "ACTIVITY4", value: 1 },
        { source: "scs-supplies-svc3", target: "LEDGER1", value: 1 },
        { source: "scs-supplies-svc3", target: "PEOPLE3", value: 1 },
        { source: "scs-supplies-svc3", target: "PEOPLE5", value: 1 },
        { source: "scs-supplies-svc3", target: "PROJECT2", value: 1 },
        { source: "scs-supplies-svc3", target: "PROJECT3", value: 1 },
        { source: "scs-supplies-svc3", target: "SSNS3", value: 1 },
        { source: "scs-supplies-svc3", target: "SSNS4", value: 1 },
        { source: "scs-supplies-svc3", target: "jvsp-calc-svc3", value: 1 },
        { source: "scs-supplies-svc3", target: "jvsp-parms-svc1", value: 1 },
        { source: "scs-supplies-svc3", target: "jvsp-parms-svc3", value: 1 },
        { source: "scs-supplies-svc3", target: "scs-supplies-svc3", value: 1 },
        { source: "scs-supplies-svc4", target: "ACCOUNT3", value: 1 },
        { source: "scs-supplies-svc4", target: "ACCOUNT5", value: 1 },
        { source: "scs-supplies-svc4", target: "ACCOUNT6", value: 1 },
        { source: "scs-supplies-svc4", target: "ACTIVITY6", value: 1 },
        { source: "scs-supplies-svc4", target: "LEDGER1", value: 1 },
        { source: "scs-supplies-svc4", target: "LEDGER3", value: 1 },
        { source: "scs-supplies-svc4", target: "LEDGER5", value: 1 },
        { source: "scs-supplies-svc4", target: "LEDGER6", value: 1 },
        { source: "scs-supplies-svc4", target: "PEOPLE1", value: 1 },
        { source: "scs-supplies-svc4", target: "PEOPLE2", value: 1 },
        { source: "scs-supplies-svc4", target: "PEOPLE4", value: 1 },
        { source: "scs-supplies-svc4", target: "PEOPLE5", value: 1 },
        { source: "scs-supplies-svc4", target: "PEOPLE6", value: 1 },
        { source: "scs-supplies-svc4", target: "PROJECT2", value: 1 },
        { source: "scs-supplies-svc4", target: "SSNS1", value: 1 },
        { source: "scs-supplies-svc4", target: "SSNS3", value: 1 },
        { source: "scs-supplies-svc4", target: "SSNS4", value: 1 },
        { source: "scs-supplies-svc4", target: "SSNS5", value: 1 },
        { source: "scs-supplies-svc4", target: "SSNS6", value: 1 },
        { source: "scs-supplies-svc4", target: "jvsp-calc-svc3", value: 1 },
        { source: "scs-supplies-svc4", target: "jvsp-calc-svc4", value: 1 },
        { source: "scs-supplies-svc4", target: "jvsp-parms-svc1", value: 1 },
        { source: "scs-supplies-svc4", target: "jvsp-parms-svc2", value: 1 },
        { source: "scs-supplies-svc4", target: "jvsp-parms-svc3", value: 1 },
        { source: "scs-supplies-svc4", target: "jvsp-parms-svc4", value: 1 },
        { source: "scs-supplies-svc4", target: "scs-supplies-svc1", value: 1 },
        { source: "scs-supplies-svc4", target: "scs-supplies-svc2", value: 1 },
        { source: "scs-supplies-svc4", target: "scs-supplies-svc4", value: 1 },
        { source: "scs-supplies-web1", target: "jvsp-calc-svc1", value: 1 },
        { source: "scs-supplies-web1", target: "jvsp-calc-svc2", value: 1 },
        { source: "scs-supplies-web1", target: "jvsp-calc-svc3", value: 1 },
        { source: "scs-supplies-web1", target: "jvsp-calc-svc4", value: 1 },
        { source: "scs-supplies-web1", target: "jvsp-parms-svc1", value: 1 },
        { source: "scs-supplies-web1", target: "jvsp-parms-svc3", value: 1 },
        { source: "scs-supplies-web1", target: "jvsp-parms-svc4", value: 1 },
        { source: "scs-supplies-web1", target: "scs-supplies-svc1", value: 1 },
        { source: "scs-supplies-web1", target: "scs-supplies-svc3", value: 1 },
        { source: "scs-supplies-web2", target: "jvsp-calc-svc1", value: 1 },
        { source: "scs-supplies-web2", target: "jvsp-calc-svc2", value: 1 },
        { source: "scs-supplies-web2", target: "jvsp-parms-svc2", value: 1 },
        { source: "scs-supplies-web2", target: "jvsp-parms-svc3", value: 1 },
        { source: "scs-supplies-web2", target: "scs-supplies-svc1", value: 1 },
        { source: "scs-supplies-web2", target: "scs-supplies-svc4", value: 1 },
        { source: "scs-supplies-web3", target: "jvsp-calc-svc1", value: 1 },
        { source: "scs-supplies-web3", target: "jvsp-calc-svc2", value: 1 },
        { source: "scs-supplies-web3", target: "jvsp-calc-svc3", value: 1 },
        { source: "scs-supplies-web3", target: "jvsp-parms-svc4", value: 1 },
        { source: "scs-supplies-web3", target: "scs-supplies-svc3", value: 1 },
        { source: "scs-supplies-web3", target: "scs-supplies-svc4", value: 1 },
        { source: "scs-supplies-web4", target: "jvsp-calc-svc1", value: 1 },
        { source: "scs-supplies-web4", target: "jvsp-calc-svc2", value: 1 },
        { source: "scs-supplies-web4", target: "jvsp-calc-svc3", value: 1 },
        { source: "scs-supplies-web4", target: "jvsp-calc-svc4", value: 1 },
        { source: "scs-supplies-web4", target: "jvsp-parms-svc2", value: 1 },
        { source: "scs-supplies-web4", target: "jvsp-parms-svc4", value: 1 },
        { source: "scs-supplies-web4", target: "scs-supplies-svc1", value: 1 },
        { source: "scs-supplies-web5", target: "jvsp-calc-svc1", value: 1 },
        { source: "scs-supplies-web5", target: "jvsp-calc-svc3", value: 1 },
        { source: "scs-supplies-web5", target: "jvsp-calc-svc4", value: 1 },
        { source: "scs-supplies-web5", target: "jvsp-parms-svc1", value: 1 },
        { source: "scs-supplies-web5", target: "jvsp-parms-svc2", value: 1 },
        { source: "scs-supplies-web5", target: "jvsp-parms-svc3", value: 1 },
        { source: "scs-supplies-web5", target: "jvsp-parms-svc4", value: 1 },
        { source: "scs-supplies-web5", target: "scs-supplies-svc1", value: 1 },
        { source: "scs-supplies-web5", target: "scs-supplies-svc2", value: 1 },
        { source: "scs-supplies-web5", target: "scs-supplies-svc3", value: 1 },
        
        
    ]
};

return dataelements;
}
